name: ShamedPlug
author: Shamed
version: 0.1.6.40
main: me.Shamed.Test.Main

depend: [ProtocolLib, ViaVersion, floodgate-bukkit, HolographicDisplays]

commands:
   Velocity:
      description: Gives you velocity.
   VeloRod:
      description: Gives you a rod that can launch you to the air and make the ground explode (not really).
